services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/mydatabase
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=secret

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
    ports:
      - 5432:5432
